name: continuous prerelease to GitHub

on:
  push:
    branches: [ main, build-stage-extension ]

  workflow_dispatch:

jobs:
  sign-tag-release:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Update translations"
        run: git submodule update --init --recursive --remote

      - name: "Set up node"
        uses: actions/setup-node@v2.4.0

      - name: "Install"
        run: npm install

      - name: "Lint"
        run: npm run lint

      - name: "Configure add-on for stage site"
        run: npm run config:stage

      - name: "Set YYYY.MM.DD.minutes version"
        id: version
        run: |
          export VERSION="$(date +%Y.%-m.%-d.)$(echo $(( $(date '+%-H *60 + %-M') )))"
          jq ".version = \"$VERSION\"" src/manifest.json > manifest.json~
          mv manifest.json~ src/manifest.json
          git diff
          echo ::set-output name=version::$(echo $VERSION)

      - name: "Sign"
        run: ./node_modules/.bin/web-ext sign -s src --channel=unlisted --api-key=${{ secrets.AMO_API_KEY }} --api-secret=${{ secrets.AMO_API_SECRET }}

      - name: "Tag"
        run: |
              git config user.name "GitHub Action: Sign, Tag, Release"
              git config user.email "<>"
              git tag ${{ steps.version.outputs.version }}
              git push origin --tags

      - name: "Make release notes"
        id: release_notes
        run: echo ::set-output name=release_notes::$(git log --no-merges --pretty=format:"%h %s" ${{ steps.version.outputs.version }}^..${{ steps.version.outputs.version }})

      - uses: actions/upload-artifact@v2
        with:
          name: fx-private-relay-stage.xpi
          path: web-ext-artifacts/firefox_relay-${{ steps.version.outputs.version }}-an+fx.xpi


      ## This should theoretically be enough to publish the extension as a GitHub Release,
      ## except for sending the actual .xpi in the body of a request using octokit/request-action.
      ## Left in as documentation in case someone wants to finish this up:
      # - name: "Release"
      #   id: create_release
      #   uses: octokit/request-action@v2.1.0
      #   with:
      #     route: POST /repos/{owner}/{repo}/releases
      #     owner: mozilla
      #     repo: fx-private-relay-add-on
      #     prerelease: true
      #     tag_name: ${{ steps.version.outputs.version }}
      #     body: ${{ steps.release_notes.outputs.release_notes }}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: "Upload extension"
      #   uses: octokit/request-action@v2.1.0
      #   with:
      #     route: POST /repos/{owner}/{repo}/releases/{release_id}/assets
      #     owner: mozilla
      #     repo: fx-private-relay-add-on
      #     release_id: ${{ fromJson(steps.create_release.outputs.data).id }}
      #     body: # TODO: Figure out how to pass the binary data of
      #           #       ./web-ext-artifacts/firefox_relay-${{ steps.version.outputs.version }}-an+fx.xpi
      #           #       here.
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
